sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  # python versions used in el7 SCL & supported fedora
  - "3.6"
  - "3.7"
env:
  - DB=postgres
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: "9.6"
services:
  - postgresql
  - redis-server
install: .travis/install.sh
before_script: .travis/before_script.sh
script: .travis/script.sh
after_failure:
  - sh -c "cat ~/django_runserver.log"
  - sh -c "cat ~/resource_manager.log"
  - sh -c "cat ~/reserved_workers-1.log"
stages:
  - name: test
#   - name: deploy
#     if: tag IS present
# jobs:
#   include:
#   - stage: deploy
#     script: skip
#     deploy:
#       provider: pypi
#       distributions: sdist bdist_wheel
#       user: pulp
#       password:
#         secure: <<<KEY>>>
#       on:
#         tags: true
