#!/bin/bash

# This script expects all <app_label>-api.json files to exist in the plugins root directory.
# It produces a <app_label>-python-client.tar file in the plugins root directory.

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_deb' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -mveuo pipefail

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../../..

pushd ../pulp-openapi-generator
rm -rf "pulp_deb-client"

./gen-client.sh "../pulp_deb/deb-api.json" "deb" python "pulp_deb"

pushd pulp_deb-client

uv build
uvx twine check "dist/pulp_deb_client-"*"-py3-none-any.whl"
uvx twine check "dist/pulp_deb_client-"*".tar.gz"
tar cvf "../../pulp_deb/deb-python-client.tar" ./dist

popd
popd
