# Generated by Django 3.2.13 on 2022-07-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('deb', '0001_initial'), ('deb', '0002_auto_20190905_1000'), ('deb', '0003_rename_package_field'), ('deb', '0004_auto_20191014_1722'), ('deb', '0005_rename_release_file'), ('deb', '0006_debrepository'), ('deb', '0007_create_metadata_models'), ('deb', '0008_debremote_gpgkey'), ('deb', '0009_apt_release_signing_service'), ('deb', '0010_debpublication_signing_service'), ('deb', '0011_rename_models_to_apt'), ('deb', '0012_auto_20200803_1337'), ('deb', '0013_aptremote_ignore_missing_package_indices'), ('deb', '0014_swap_distribution_model'), ('deb', '0015_add_custom_fields_to_packages'), ('deb', '0016_switch_to_newer_jsonfield_model'), ('deb', '0017_allow_longer_string_lists'), ('deb', '0018_textfield_conversion'), ('deb', '0019_immutable_metadata_constraints')]

    initial = True

    dependencies = [
        ('core', '0091_systemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_genericcontent', serialize=False, to='core.content')),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_package', serialize=False, to='core.content')),
                ('package', models.TextField()),
                ('source', models.TextField(null=True)),
                ('version', models.TextField()),
                ('architecture', models.TextField()),
                ('section', models.TextField(null=True)),
                ('priority', models.TextField(null=True)),
                ('origin', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('bugs', models.TextField(null=True)),
                ('essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('build_essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('installed_size', models.IntegerField(null=True)),
                ('maintainer', models.TextField()),
                ('original_maintainer', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_md5', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('built_using', models.TextField(null=True)),
                ('auto_built_package', models.TextField(null=True)),
                ('multi_arch', models.TextField(choices=[('no', 'no'), ('same', 'same'), ('foreign', 'foreign'), ('allowed', 'allowed')], null=True)),
                ('breaks', models.TextField(null=True)),
                ('conflicts', models.TextField(null=True)),
                ('depends', models.TextField(null=True)),
                ('recommends', models.TextField(null=True)),
                ('suggests', models.TextField(null=True)),
                ('enhances', models.TextField(null=True)),
                ('pre_depends', models.TextField(null=True)),
                ('provides', models.TextField(null=True)),
                ('replaces', models.TextField(null=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.TextField()),
                ('custom_fields', models.JSONField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseFile',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_releasefile', serialize=False, to='core.content')),
                ('codename', models.TextField()),
                ('suite', models.TextField()),
                ('distribution', models.TextField()),
                ('components', models.TextField(blank=True)),
                ('architectures', models.TextField(blank=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('artifact_set_sha256', models.CharField(max_length=255)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('codename', 'suite', 'distribution', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='InstallerFileIndex',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_installerfileindex', serialize=False, to='core.content')),
                ('component', models.TextField()),
                ('architecture', models.TextField()),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_installerfileindex', to='deb.releasefile')),
            ],
            options={
                'verbose_name_plural': 'InstallerFileIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageIndex',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_packageindex', serialize=False, to='core.content')),
                ('component', models.TextField()),
                ('architecture', models.TextField()),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_packageindex', to='deb.releasefile')),
                ('artifact_set_sha256', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'PackageIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', 'artifact_set_sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_release', serialize=False, to='core.content')),
                ('codename', models.TextField()),
                ('suite', models.TextField()),
                ('distribution', models.TextField()),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('codename', 'suite', 'distribution')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_releasecomponent', serialize=False, to='core.content')),
                ('component', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_releasecomponent', to='deb.release')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('component', 'release')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseArchitecture',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_releasearchitecture', serialize=False, to='core.content')),
                ('architecture', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_releasearchitecture', to='deb.release')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('architecture', 'release')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_packagereleasecomponent', serialize=False, to='core.content')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_packagereleasecomponent', to='deb.package')),
                ('release_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_packagereleasecomponent', to='deb.releasecomponent')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('package', 'release_component')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='AptReleaseSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.signingservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.signingservice',),
        ),
        migrations.CreateModel(
            name='AptPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptpublication', serialize=False, to='core.publication')),
                ('simple', models.BooleanField(default=False)),
                ('structured', models.BooleanField(default=False)),
                ('signing_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deb_aptpublication', to='deb.aptreleasesigningservice')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='AptRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptrepository', serialize=False, to='core.repository')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.repository',),
        ),
        migrations.CreateModel(
            name='VerbatimPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_verbatimpublication', serialize=False, to='core.publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='AptDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptdistribution', serialize=False, to='core.distribution')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.distribution',),
        ),
        migrations.CreateModel(
            name='InstallerPackage',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_installerpackage', serialize=False, to='core.content')),
                ('package', models.TextField()),
                ('source', models.TextField(null=True)),
                ('version', models.TextField()),
                ('architecture', models.TextField()),
                ('section', models.TextField(null=True)),
                ('priority', models.TextField(null=True)),
                ('origin', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('bugs', models.TextField(null=True)),
                ('essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('build_essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('installed_size', models.IntegerField(null=True)),
                ('maintainer', models.TextField()),
                ('original_maintainer', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_md5', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('built_using', models.TextField(null=True)),
                ('auto_built_package', models.TextField(null=True)),
                ('multi_arch', models.TextField(choices=[('no', 'no'), ('same', 'same'), ('foreign', 'foreign'), ('allowed', 'allowed')], null=True)),
                ('breaks', models.TextField(null=True)),
                ('conflicts', models.TextField(null=True)),
                ('depends', models.TextField(null=True)),
                ('recommends', models.TextField(null=True)),
                ('suggests', models.TextField(null=True)),
                ('enhances', models.TextField(null=True)),
                ('pre_depends', models.TextField(null=True)),
                ('provides', models.TextField(null=True)),
                ('replaces', models.TextField(null=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.TextField()),
                ('custom_fields', models.JSONField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='AptRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptremote', serialize=False, to='core.remote')),
                ('distributions', models.TextField(null=True)),
                ('components', models.TextField(null=True)),
                ('architectures', models.TextField(null=True)),
                ('sync_sources', models.BooleanField(default=False)),
                ('sync_udebs', models.BooleanField(default=False)),
                ('sync_installer', models.BooleanField(default=False)),
                ('gpgkey', models.TextField(null=True)),
                ('ignore_missing_package_indices', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.remote',),
        ),
    ]
