# Generated by Django 4.2.23 on 2025-08-14 11:10

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base
import pulpcore.app.util


class Migration(migrations.Migration):

    replaces = [('deb', '0001_initial'), ('deb', '0002_auto_20190905_1000'), ('deb', '0003_rename_package_field'), ('deb', '0004_auto_20191014_1722'), ('deb', '0005_rename_release_file'), ('deb', '0006_debrepository'), ('deb', '0007_create_metadata_models'), ('deb', '0008_debremote_gpgkey'), ('deb', '0009_apt_release_signing_service'), ('deb', '0010_debpublication_signing_service'), ('deb', '0011_rename_models_to_apt'), ('deb', '0012_auto_20200803_1337'), ('deb', '0013_aptremote_ignore_missing_package_indices'), ('deb', '0014_swap_distribution_model'), ('deb', '0015_add_custom_fields_to_packages'), ('deb', '0016_switch_to_newer_jsonfield_model'), ('deb', '0017_allow_longer_string_lists'), ('deb', '0018_textfield_conversion'), ('deb', '0019_immutable_metadata_constraints'), ('deb', '0020_remove_fk_relations_in_packageindex_and_installerfileindex'), ('deb', '0021_remove_release_from_structure_types'), ('deb', '0022_alter_aptdistribution_distribution_ptr_and_more'), ('deb', '0023_add_default_signing_services'), ('deb', '0024_add_release_fields'), ('deb', '0025_merge_colliding_structure_content'), ('deb', '0026_aptrepository_publish_upstream_release_fields'), ('deb', '0027_alter_aptpublication_structured'), ('deb', '0028_sourcepackage_sourcepackagereleasecomponent_and_more'), ('deb', '0029_distributedpublication'), ('deb', '0030_rbac_permissions'), ('deb', '0031_add_domains')]

    initial = True

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbatimPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.publication')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'permissions': [
                    ('manage_roles_verbatimpublication', 'Can manage roles on a verbatim publication'),
                ],
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='AptReleaseSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.signingservice')),
            ],
            options={'abstract': False,},
            bases=('core.signingservice',),
        ),
        migrations.CreateModel(
            name='AptPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.publication')),
                ('simple', models.BooleanField(default=False)),
                ('structured', models.BooleanField(default=True)),
                ('signing_service', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='deb.aptreleasesigningservice')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'permissions': [
                    ('manage_roles_aptpublication', 'Can manage roles on an APT publication'),
                ],
            },
            bases=('core.publication',),
        ),
        migrations.CreateModel(
            name='AptRepository',
            fields=[
                ('repository_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.repository')),
                ('publish_upstream_release_fields', models.BooleanField(default=True)),
                ('signing_service', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='deb.aptreleasesigningservice')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'permissions': [
                    ('manage_roles_aptrepository', 'Can manage roles on APT repositories'),
                    ('modify_content_aptrepository', 'Add content to, or remove content from a repository'),
                    ('repair_aptrepository', 'Copy an APT repository'),
                    ('sync_aptrepository', 'Sync an APT repository'),
                    ('delete_aptrepository_version', 'Delete a repository version'),
                ],
            },
            bases=('core.repository',),
        ),
        migrations.CreateModel(
            name='AptRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.remote')),
                ('distributions', models.TextField(null=True)),
                ('components', models.TextField(null=True)),
                ('architectures', models.TextField(null=True)),
                ('sync_sources', models.BooleanField(default=False)),
                ('sync_udebs', models.BooleanField(default=False)),
                ('sync_installer', models.BooleanField(default=False)),
                ('gpgkey', models.TextField(null=True)),
                ('ignore_missing_package_indices', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'permissions': [
                    ('manage_roles_aptremote', 'Can manage roles on an APT remote'),
                ],
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='AptDistribution',
            fields=[
                ('distribution_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.distribution')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'permissions': [
                    ('manage_roles_aptdistribution', 'Can manage roles on an APT distribution'),
                ],
            },
            bases=('core.distribution',),
        ),

        migrations.CreateModel(
            name='GenericContent',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('package', models.TextField()),
                ('source', models.TextField(null=True)),
                ('version', models.TextField()),
                ('architecture', models.TextField()),
                ('section', models.TextField(null=True)),
                ('priority', models.TextField(null=True)),
                ('origin', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('bugs', models.TextField(null=True)),
                ('essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('build_essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('installed_size', models.IntegerField(null=True)),
                ('maintainer', models.TextField()),
                ('original_maintainer', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_md5', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('built_using', models.TextField(null=True)),
                ('auto_built_package', models.TextField(null=True)),
                ('multi_arch', models.TextField(choices=[('no', 'no'), ('same', 'same'), ('foreign', 'foreign'), ('allowed', 'allowed')], null=True)),
                ('breaks', models.TextField(null=True)),
                ('conflicts', models.TextField(null=True)),
                ('depends', models.TextField(null=True)),
                ('recommends', models.TextField(null=True)),
                ('suggests', models.TextField(null=True)),
                ('enhances', models.TextField(null=True)),
                ('pre_depends', models.TextField(null=True)),
                ('provides', models.TextField(null=True)),
                ('replaces', models.TextField(null=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.TextField()),
                ('custom_fields', models.JSONField(null=True)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='InstallerPackage',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('package', models.TextField()),
                ('source', models.TextField(null=True)),
                ('version', models.TextField()),
                ('architecture', models.TextField()),
                ('section', models.TextField(null=True)),
                ('priority', models.TextField(null=True)),
                ('origin', models.TextField(null=True)),
                ('tag', models.TextField(null=True)),
                ('bugs', models.TextField(null=True)),
                ('essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('build_essential', models.BooleanField(choices=[(True, 'yes'), (False, 'no')], null=True)),
                ('installed_size', models.IntegerField(null=True)),
                ('maintainer', models.TextField()),
                ('original_maintainer', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_md5', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('built_using', models.TextField(null=True)),
                ('auto_built_package', models.TextField(null=True)),
                ('multi_arch', models.TextField(choices=[('no', 'no'), ('same', 'same'), ('foreign', 'foreign'), ('allowed', 'allowed')], null=True)),
                ('breaks', models.TextField(null=True)),
                ('conflicts', models.TextField(null=True)),
                ('depends', models.TextField(null=True)),
                ('recommends', models.TextField(null=True)),
                ('suggests', models.TextField(null=True)),
                ('enhances', models.TextField(null=True)),
                ('pre_depends', models.TextField(null=True)),
                ('provides', models.TextField(null=True)),
                ('replaces', models.TextField(null=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.TextField()),
                ('custom_fields', models.JSONField(null=True)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('codename', models.TextField()),
                ('suite', models.TextField()),
                ('distribution', models.TextField()),
                ('version', models.TextField(default='__!!!NULL VALUE!!!__')),
                ('origin', models.TextField(default='__!!!NULL VALUE!!!__')),
                ('label', models.TextField(default='__!!!NULL VALUE!!!__')),
                ('description', models.TextField(default='__!!!NULL VALUE!!!__')),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('component', models.TextField()),
                ('distribution', models.TextField()),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('distribution', 'component', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseArchitecture',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('architecture', models.TextField()),
                ('distribution', models.TextField()),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('distribution', 'architecture', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ReleaseFile',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('codename', models.TextField()),
                ('suite', models.TextField()),
                ('distribution', models.TextField()),
                ('components', models.TextField(blank=True)),
                ('architectures', models.TextField(blank=True)),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('artifact_set_sha256', models.CharField(max_length=255)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('codename', 'suite', 'distribution', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='InstallerFileIndex',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('component', models.TextField()),
                ('architecture', models.TextField()),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'verbose_name_plural': 'InstallerFileIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageIndex',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('component', models.TextField()),
                ('architecture', models.TextField()),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('artifact_set_sha256', models.CharField(max_length=255)),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'verbose_name_plural': 'PackageIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', 'artifact_set_sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='PackageReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('package', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='deb.package')),
                ('release_component', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='deb.releasecomponent')),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=models.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('package', 'release_component', '_pulp_domain')},
            },
            bases=('core.content',),
        ),

        migrations.CreateModel(
            name='SourcePackage',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('relative_path', models.TextField()),
                ('format', models.TextField()),
                ('source', models.TextField()),
                ('binary', models.TextField(null=True)),
                ('architecture', models.TextField(null=True)),
                ('version', models.TextField()),
                ('maintainer', models.TextField()),
                ('uploaders', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('vcs_browser', models.TextField(null=True)),
                ('vcs_arch', models.TextField(null=True)),
                ('vcs_bzr', models.TextField(null=True)),
                ('vcs_cvs', models.TextField(null=True)),
                ('vcs_darcs', models.TextField(null=True)),
                ('vcs_git', models.TextField(null=True)),
                ('vcs_hg', models.TextField(null=True)),
                ('vcs_mtn', models.TextField(null=True)),
                ('vcs_snv', models.TextField(null=True)),
                ('testsuite', models.TextField(null=True)),
                ('dgit', models.TextField(null=True)),
                ('standards_version', models.TextField()),
                ('build_depends', models.TextField(null=True)),
                ('build_depends_indep', models.TextField(null=True)),
                ('build_depends_arch', models.TextField(null=True)),
                ('build_conflicts', models.TextField(null=True)),
                ('build_conflicts_indep', models.TextField(null=True)),
                ('build_conflicts_arch', models.TextField(null=True)),
                ('package_list', models.TextField(null=True)),
            ],
            options={'default_related_name': '%(app_label)s_%(model_name)s'},
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='SourceIndex',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('component', models.CharField(max_length=255)),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deb.releasefile')),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='core.domain')),
            ],
            options={
                'verbose_name_plural': 'SourceIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256', '_pulp_domain')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='SourcePackageReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='core.content')),
                ('release_component', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='deb.releasecomponent')),
                ('source_package', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='deb.sourcepackage')),
                ('_pulp_domain', models.ForeignKey(
                    default=pulpcore.app.util.get_domain_pk,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='core.domain')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('source_package', 'release_component', '_pulp_domain')},
            },
            bases=('core.content',),
        ),

        migrations.CreateModel(
            name='AptRepositoryReleaseServiceOverride',
            fields=[
                ('pulp_id', models.UUIDField(
                    default=pulpcore.app.models.base.pulp_uuid,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('release_distribution', models.TextField()),
                ('repository', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signing_service_release_overrides',
                    to='deb.aptrepository')),
                ('signing_service', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='deb.aptreleasesigningservice')),
            ],
            options={
                'unique_together': {('repository', 'release_distribution')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DistributedPublication',
            fields=[
                ('pulp_id', models.UUIDField(
                    default=pulpcore.app.models.base.pulp_uuid,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('distribution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.distribution')),
                ('publication', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.publication')),
            ],
            options={'abstract': False},
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
