# Generated by Django 2.2.5 on 2019-09-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installerpackage',
            unique_together={('relative_path', 'sha256')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('relative_path', 'sha256')},
        ),
    ]
