# Generated by Django 2.2.5 on 2019-09-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0002_auto_20190905_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installerpackage',
            old_name='package_name',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='package',
        ),
    ]
