# Generated by Django 2.2.6 on 2019-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0003_rename_package_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcontent',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='installerfileindex',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='installerpackage',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='relative_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='relative_path',
            field=models.TextField(),
        ),
    ]
