# Generated by Django 4.2.16 on 2024-12-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0004_auto_20191014_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Release',
            new_name='ReleaseFile',
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_releasefile', serialize=False, to='core.content'),
        ),
        migrations.AlterField(
            model_name='installerfileindex',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_installerfileindex', to='deb.releasefile'),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_packageindex', to='deb.releasefile'),
        ),
    ]
