# Generated by Django 2.2.6 on 2019-10-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0004_auto_20191014_1722'),
    ]

    operations = [
        migrations.RenameModel('Release', 'ReleaseFile'),
        migrations.AlterField(
            model_name='releasefile',
            name='content_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_releasefile', serialize=False, to='core.Content'),
        ),
        migrations.AlterField(
            model_name='installerfileindex',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_installerfileindex', to='deb.ReleaseFile'),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deb_packageindex', to='deb.ReleaseFile'),
        ),
    ]
