# Generated by Django 2.2.8 on 2020-01-02 14:37

from django.db import migrations
import pulp_deb.app.models.content


class Migration(migrations.Migration):

    dependencies = [
        ('deb', 'debversion_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installerpackage',
            name='version',
            field=pulp_deb.app.models.content.DebVersionField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=pulp_deb.app.models.content.DebVersionField(max_length=255),
        ),
    ]
