# Generated by Django 2.2.10 on 2020-02-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_signing_service_foreign_key'),
        ('deb', '0008_debremote_gpgkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpublication',
            name='signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deb_debpublication', to='core.SigningService'),
        ),
    ]
