# Generated by Django 2.2.11 on 2020-03-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0009_apt_release_signing_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpublication',
            name='signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deb_debpublication', to='deb.AptReleaseSigningService'),
        ),
    ]
