# Generated by Django 2.2.16 on 2020-11-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0012_auto_20200803_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptremote',
            name='ignore_missing_package_indices',
            field=models.BooleanField(default=False),
        ),
    ]
