# Generated by Django 2.2.19 on 2021-02-24 14:57

from django.db import migrations, models
import django.db.models.deletion


def populate_publish_settings(apps, schema_editor):
    AptPublication = apps.get_model('deb', 'aptpublication')
    AptPublishSettings = apps.get_model('deb', 'aptpublishsettings')

    for publication in AptPublication.objects.all():
        publish_settings, _ = AptPublishSettings.objects.get_or_create(
            simple=publication.simple,
            structured=publication.structured,
            signing_service=publication.signing_service,
        )
        publication.publish_settings = publish_settings
        publication.save()


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0013_aptremote_ignore_missing_package_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptPublishSettings',
            fields=[
                ('publishsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='deb_aptpublishsettings', serialize=False, to='core.PublishSettings')),
                ('simple', models.BooleanField(default=False)),
                ('structured', models.BooleanField(default=False)),
                ('signing_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deb_aptpublishsettings', to='deb.AptReleaseSigningService')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('simple', 'structured', 'signing_service')},
            },
            bases=('core.publishsettings',),
        ),
        migrations.RunPython(populate_publish_settings),
    ]
