# Generated by Django 2.2.20 on 2021-06-07 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0014_swap_distribution_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerpackage',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
