# Generated by Django 3.2.6 on 2021-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0015_add_custom_fields_to_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installerpackage',
            name='custom_fields',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='custom_fields',
            field=models.JSONField(null=True),
        ),
    ]
