# Generated by Django 3.2.8 on 2021-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0016_switch_to_newer_jsonfield_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptremote',
            name='architectures',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aptremote',
            name='components',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aptremote',
            name='distributions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='architectures',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='releasefile',
            name='components',
            field=models.TextField(blank=True),
        ),
    ]
