# Generated by Django 3.2.13 on 2022-06-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0018_textfield_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageindex',
            name='artifact_set_sha256',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='releasefile',
            name='artifact_set_sha256',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='packageindex',
            unique_together={('relative_path', 'sha256', 'artifact_set_sha256')},
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together={('codename', 'suite', 'distribution', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256')},
        ),
    ]
