# Generated by Django 3.2.16 on 2023-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0021_remove_release_from_structure_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='label',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='origin',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='description',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='label',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='origin',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='version',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description')},
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256')},
        ),
        # create the field with a default of False so that the field is populated as False for
        # existing models but then set the default to True for new remotes going forward
        migrations.AddField(
            model_name='aptremote',
            name='sync_extra_release_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aptremote',
            name='sync_extra_release_fields',
            field=models.BooleanField(default=True),
        ),
    ]
