# Generated by Django 4.2.1 on 2023-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0023_add_default_signing_services'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='release',
            name='description',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='label',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='origin',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AddField(
            model_name='release',
            name='version',
            field=models.TextField(default='__!!!NULL VALUE!!!__'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description')},
        ),
    ]
