# Generated by Django 4.2.2 on 2023-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0025_merge_colliding_structure_content'),
    ]

    operations = [
         # create the field with a default of False so that the field is populated as False for
         # existing models but then set the default to True for new repositories going forward
         migrations.AddField(
            model_name='aptrepository',
            name='publish_upstream_release_fields',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aptrepository',
            name='publish_upstream_release_fields',
            field=models.BooleanField(default=True),
        ),
    ]
