# Generated by Django 4.2.3 on 2023-08-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0026_aptrepository_publish_upstream_release_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptpublication',
            name='structured',
            field=models.BooleanField(default=True),
        ),
    ]
