# Generated by Django 4.2.6 on 2023-10-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_distribution_hidden'),
        ('deb', '0027_alter_aptpublication_structured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePackage',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('relative_path', models.TextField()),
                ('format', models.TextField()),
                ('source', models.TextField()),
                ('binary', models.TextField(null=True)),
                ('architecture', models.TextField(null=True)),
                ('version', models.TextField()),
                ('maintainer', models.TextField()),
                ('uploaders', models.TextField(null=True)),
                ('homepage', models.TextField(null=True)),
                ('vcs_browser', models.TextField(null=True)),
                ('vcs_arch', models.TextField(null=True)),
                ('vcs_bzr', models.TextField(null=True)),
                ('vcs_cvs', models.TextField(null=True)),
                ('vcs_darcs', models.TextField(null=True)),
                ('vcs_git', models.TextField(null=True)),
                ('vcs_hg', models.TextField(null=True)),
                ('vcs_mtn', models.TextField(null=True)),
                ('vcs_snv', models.TextField(null=True)),
                ('testsuite', models.TextField(null=True)),
                ('dgit', models.TextField(null=True)),
                ('standards_version', models.TextField()),
                ('build_depends', models.TextField(null=True)),
                ('build_depends_indep', models.TextField(null=True)),
                ('build_depends_arch', models.TextField(null=True)),
                ('build_conflicts', models.TextField(null=True)),
                ('build_conflicts_indep', models.TextField(null=True)),
                ('build_conflicts_arch', models.TextField(null=True)),
                ('package_list', models.TextField(null=True)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='SourcePackageReleaseComponent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('release_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deb.releasecomponent')),
                ('source_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deb.sourcepackage')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('source_package', 'release_component')},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='SourceIndex',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.content')),
                ('component', models.CharField(max_length=255)),
                ('relative_path', models.TextField()),
                ('sha256', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deb.releasefile')),
            ],
            options={
                'verbose_name_plural': 'SourceIndices',
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('relative_path', 'sha256')},
            },
            bases=('core.content',),
        ),
    ]
