# Generated by Django 4.2.2 on 2024-01-03 18:58

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_remove_task_args_remove_task_kwargs"),
        ("deb", "0028_sourcepackage_sourcepackagereleasecomponent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributedPublication",
            fields=[
                (
                    "pulp_id",
                    models.UUIDField(
                        default=pulpcore.app.models.base.pulp_uuid,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pulp_created", models.DateTimeField(auto_now_add=True)),
                ("pulp_last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.distribution"
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.publication"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
