# Generated by Django 4.2.21 on 2025-06-26 07:53

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_distribution_checkpoint_publication_checkpoint'),
        ('deb', '0030_rbac_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genericcontent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='installerfileindex',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='installerpackage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='packageindex',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='releasearchitecture',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='releasecomponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sourceindex',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sourcepackagereleasecomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genericcontent',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='installerfileindex',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='installerpackage',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='package',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packageindex',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='packagereleasecomponent',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='release',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='releasearchitecture',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='releasecomponent',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='sourceindex',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AddField(
            model_name='sourcepackagereleasecomponent',
            name='_pulp_domain',
            field=models.ForeignKey(default=pulpcore.app.util.get_domain_pk, on_delete=django.db.models.deletion.PROTECT, to='core.domain'),
        ),
        migrations.AlterUniqueTogether(
            name='genericcontent',
            unique_together={('relative_path', 'sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='installerfileindex',
            unique_together={('relative_path', 'sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='installerpackage',
            unique_together={('relative_path', 'sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('relative_path', 'sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packageindex',
            unique_together={('relative_path', 'sha256', 'artifact_set_sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together={('package', 'release_component', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='releasearchitecture',
            unique_together={('distribution', 'architecture', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='releasecomponent',
            unique_together={('distribution', 'component', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='releasefile',
            unique_together={('codename', 'suite', 'distribution', 'components', 'architectures', 'relative_path', 'sha256', 'artifact_set_sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='sourceindex',
            unique_together={('relative_path', 'sha256', '_pulp_domain')},
        ),
        migrations.AlterUniqueTogether(
            name='sourcepackagereleasecomponent',
            unique_together={('source_package', 'release_component', '_pulp_domain')},
        ),
    ]
