# Generated by Django 5.2.5 on 2025-09-22 08:54

import django.db.models.deletion
import pulpcore.app.models.access_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0001_initial_squashed_0031_add_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptAlternateContentSource',
            fields=[
                ('alternatecontentsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.alternatecontentsource')),
            ],
            options={
                'permissions': [('refresh_aptalternatecontentsource', 'Refresh an Alternate Content Source'), ('manage_roles_aptalternatecontentsource', 'Can manage roles on ACS')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.alternatecontentsource', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
