# Generated by Django 4.2.25 on 2025-10-23 21:43

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import pulpcore.app.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_domainize_import_export'),
        ('deb', '0001_initial_squashed_0031_add_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptPackageSigningService',
            fields=[
                ('signingservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.signingservice')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.signingservice',),
        ),
        migrations.AddField(
            model_name='aptrepository',
            name='package_signing_fingerprint',
            field=models.TextField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aptrepository',
            name='package_signing_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deb.aptpackagesigningservice'),
        ),
        migrations.CreateModel(
            name='AptRepositoryReleasePackageSigningFingerprintOverride',
            fields=[
                ('pulp_id', models.UUIDField(default=pulpcore.app.models.base.pulp_uuid, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('package_signing_fingerprint', models.TextField(max_length=40)),
                ('release_distribution', models.TextField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_signing_fingerprint_release_overrides', to='deb.aptrepository')),
            ],
            options={
                'unique_together': {('repository', 'release_distribution')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
