# Generated by Django 4.2.25 on 2025-10-28 14:42

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.models.access_policy


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0032_add_autopublish'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptAlternateContentSource',
            fields=[
                ('alternatecontentsource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.alternatecontentsource')),
            ],
            options={
                'permissions': [('refresh_aptalternatecontentsource', 'Refresh an Alternate Content Source'), ('manage_roles_aptalternatecontentsource', 'Can manage roles on ACS')],
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.alternatecontentsource', pulpcore.app.models.access_policy.AutoAddObjPermsMixin),
        ),
    ]
