# Generated by Django 4.2.27 on 2025-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0033_aptalternatecontentsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptpublication',
            name='layout',
            field=models.TextField(choices=[('nested_alphabetically', 'nested_alphabetically'), ('nested_by_digest', 'nested_by_digest'), ('nested_by_both', 'nested_by_both')], default='nested_alphabetically'),
        ),
    ]
