# Generated by Django 5.2.10 on 2026-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0034_aptpublication_layout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='packagereleasecomponent',
            name='index_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasearchitecture',
            name='base_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='releasearchitecture',
            name='variant_architecture',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='packagereleasecomponent',
            unique_together={('package', 'release_component', 'index_architecture', '_pulp_domain')},
        ),
    ]
