# Generated by Django 5.2.12 on 2026-04-06 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deb", "0038_signing_fingerprint_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="installerpackage",
            name="signing_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="signing_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=None, null=True, size=None
            ),
        ),
    ]
