# Generated by Django 5.2.12 on 2026-07-20 07:37

from collections.abc import Mapping
import hashlib
import json
from typing import Any

from django.db import migrations, models, transaction
from django.db.models import Count


BATCH_SIZE = 5000

PACKAGE_METADATA_FIELDS = (
    "package",
    "source",
    "version",
    "architecture",
    "architecture_variant",
    "section",
    "priority",
    "origin",
    "tag",
    "bugs",
    "essential",
    "build_essential",
    "installed_size",
    "maintainer",
    "original_maintainer",
    "description",
    "description_md5",
    "homepage",
    "built_using",
    "auto_built_package",
    "multi_arch",
    "breaks",
    "conflicts",
    "depends",
    "recommends",
    "suggests",
    "enhances",
    "pre_depends",
    "provides",
    "replaces",
    "custom_fields",
)


def _normalize_value(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {
            str(key): _normalize_value(value[key])
            for key in sorted(value, key=str)
        }
    if isinstance(value, (list, tuple)):
        return [_normalize_value(item) for item in value]
    return value


def _metadata_sha256(package):
    metadata = {}
    for field_name in PACKAGE_METADATA_FIELDS:
        value = getattr(package, field_name)

        if field_name == "custom_fields":
            value = value or {}
        elif field_name == "installed_size" and value is not None:
            value = int(value)

        metadata[field_name] = _normalize_value(value)

    payload = json.dumps(
        metadata,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")

    return hashlib.sha256(payload).hexdigest()


def populate_metadata_sha256(apps, schema_editor):
    database = schema_editor.connection.alias

    for model_name in ("Package", "InstallerPackage"):
        model = apps.get_model("deb", model_name)
        last_pk = None

        while True:
            queryset = (
                model.objects.using(database)
                .filter(metadata_sha256__isnull=True)
                .order_by("pk")
                .only("pk", *PACKAGE_METADATA_FIELDS)
            )

            if last_pk is not None:
                queryset = queryset.filter(pk__gt=last_pk)

            batch = list(queryset[:BATCH_SIZE])

            if not batch:
                break

            for package in batch:
                package.metadata_sha256 = _metadata_sha256(package)

            with transaction.atomic(using=database):
                model.objects.using(database).bulk_update(
                    batch,
                    ["metadata_sha256"],
                    batch_size=BATCH_SIZE,
                )

            last_pk = batch[-1].pk


def validate_metadata_sha256(apps, schema_editor):
    database = schema_editor.connection.alias

    for model_name in ("Package", "InstallerPackage"):
        model = apps.get_model("deb", model_name)

        null_count = (
            model.objects.using(database)
            .filter(metadata_sha256__isnull=True)
            .count()
        )

        if null_count:
            raise RuntimeError(
                f"{model_name} has {null_count} rows "
                "without metadata_sha256"
            )

        duplicates = (
            model.objects.using(database)
            .values(
                "relative_path",
                "sha256",
                "metadata_sha256",
                "_pulp_domain",
            )
            .annotate(row_count=Count("pk"))
            .filter(row_count__gt=1)
        )

        if duplicates.exists():
            raise RuntimeError(
                f"{model_name} has duplicate metadata identities"
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("deb", "0040_architecture_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="installerpackage",
            name="metadata_sha256",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="metadata_sha256",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(populate_metadata_sha256, migrations.RunPython.noop),
        migrations.RunPython(validate_metadata_sha256, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="installerpackage",
            name="metadata_sha256",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name="package",
            name="metadata_sha256",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="installerpackage",
            unique_together={
                ("relative_path", "sha256", "metadata_sha256", "_pulp_domain")
            },
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={
                ("relative_path", "sha256", "metadata_sha256", "_pulp_domain")
            },
        ),
    ]
