# Generated by Django 5.2.12 on 2026-07-07 07:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deb", "0041_package_metadata_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptpublication",
            name="excluded_package_metadata_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="aptremote",
            name="excluded_package_metadata_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="aptrepository",
            name="excluded_package_metadata_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, size=None
            ),
        ),
    ]
