# Generated by Django 5.2.12 on 2026-09-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deb", "0042_add_excluded_package_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptpublication",
            name="no_support_for_architecture_all",
            field=models.BooleanField(default=False),
        ),
    ]
