# Generated by Django 5.2.17 on 2026-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deb', '0042_add_excluded_package_metadata_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='release',
            name='but_automatic_upgrades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='not_automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('codename', 'suite', 'distribution', 'version', 'origin', 'label', 'description', 'not_automatic', 'but_automatic_upgrades', '_pulp_domain')},
        ),
    ]
